export const PORT = 'PORT';
export const JWT_SECRET_KEY = 'JWT_SECRET_KEY';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_PASSWORD = 'REGISTER_PASSWORD';
export const ALLOW_REGISTER = 'ALLOW_REGISTER';