export const PORT = 'PORT';
export const JWT_SECRET_KEY = 'JWT_SECRET_KEY';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_PASSWORD = 'REGISTER_PASSWORD';
export const ALLOW_REGISTER = 'ALLOW_REGISTER';
export const DB_PATH = 'DB_PATH';
export const AI_KEY = 'AI_KEY';
export const TAG_PROMPT_RULES = 'TAG_PROMPT_RULES';
export const TAG_PROMPT_TEMPERATURE = 'TAG_PROMPT_TEMPERATURE';
export const TAG_PROMPT_MAX_TOKENS = 'TAG_PROMPT_MAX_TOKENS';

